services:
  radiobot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - ./data:/app/data
    network_mode: host
    restart: unless-stopped
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
